# Generated by Django 2.0.4 on 2018-07-01 02:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='games_played',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='hire_price',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(default='settings.MEDIA_ROOT/profile_pics/default_profile_pic.png', storage=django.core.files.storage.FileSystemStorage(location='/Users/mpeixoto/PycharmProjects/MaxBoost/media/'), upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_online',
            field=models.FloatField(default='0.0'),
        ),
    ]
