# Generated by Django 2.0.4 on 2018-08-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180708_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(upload_to='game_pics'),
        ),
    ]
