# Generated by Django 2.1 on 2018-09-03 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180817_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22)),
                ('platform', models.CharField(choices=[('1', 'PS4'), ('2', 'Xbox One'), ('3', 'PC'), ('4', 'Switch')], max_length=1)),
                ('times_played', models.IntegerField()),
                ('hours_played', models.DurationField()),
                ('level', models.CharField(max_length=22)),
                ('game_title', models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.PROTECT, related_name='stat', to='main.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=22)),
                ('receiver', models.CharField(max_length=22)),
                ('subject', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=600)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='games_played',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='game_playing',
            field=models.ForeignKey(blank=True, db_column='title', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_playing', to='main.Game'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='', max_length=44, verbose_name='password2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='/profile_pics/default_profile_pic.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=22, verbose_name='username'),
        ),
    ]
